=== rafalh/mtasa_toxic/toxic/lang/strings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="strings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="msg" type="msg" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="msg">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="id" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== rafalh/mtasa_toxic/toxic/lang/de_c.xml
<?xml version="1.0" encoding="UTF-8"?>
<strings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="strings.xsd">
    <msg id="* %s has left the game.">* %s hat das Spiel verlassen.</msg>
    <msg id="* %s has been kicked from the game.">* %s wurde vom Spiel gekickt.</msg>
    <msg id="* %s has been banned from the game.">* %s wurde vom Spiel gebannt.</msg>
    <msg id="* %s has left the game [%s].">* %s hat das Spiel verlassen [%s].</msg>
    
    <msg id="Usage: %s">Nutzung: %s</msg>
    <msg id="Press %s to open User Panel and %s to open Statistics Panel!">Druecke %s um dein User Panel zu oeffnen und %s um dein Statistiken Panel zu oeffnen!</msg>
    
    <msg id="Statistics">Statistiken</msg>
    <msg id="Player:">Spieler:</msg>
    <msg id="Cash:">Geld:</msg>
    <msg id="Points:">Punkte:</msg>
    <msg id="Rank:">Rang:</msg>
    <msg id="Top Times held:">Schnellste Zeiten:</msg>
    <msg id="Bidlevel:">Bidlevel:</msg>
    <msg id="Exploded:">Explodiert:</msg>
    <msg id="Drowned:">Ertrunken:</msg>
    <msg id="Playtime:">Spielzeit:</msg>
    
    <msg id="Profile">Profil</msg>
    
    <msg id="Players online only">Online Spieler</msg>
    
    <msg id="Shop">Laden</msg>
    <msg id="Cost:">Kostet:</msg>
    <msg id="Buy">Kaufen</msg>
    <msg id="Sell">Verkaufen</msg>
    <msg id="Use">Benutzen</msg>
    <msg id="Description:">Beschreibung:</msg>
    
    <msg id="Settings">Einstellungen</msg>
    <msg id="Language:">Sprache:</msg>
    
    <msg id="Save">Speichern</msg>
    <msg id="Color">Farbe</msg>
    <msg id="Close">Schliessen</msg>
    <msg id="Pos">Pos</msg>
    <msg id="Time">Zeit</msg>
    
    <msg id="Private Chat - %s">Privater Chat - %s</msg>
    <msg id="Say:">Sagen:</msg>
    <msg id="Send">Senden</msg>
    <msg id="In background">Im Hintergrund</msg>
    
    <msg id="User Panel">User Panel</msg>
    <msg id="Top Times:">Top Times:</msg>
    <msg id="none">Keiner</msg>
</strings>
