=== rafalh/mtasa_toxic/toxic/conf/xsd/shop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="shop">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item" type="item" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="item">
    <xs:sequence>
      <xs:element name="param" type="itemParam" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="price" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="itemParam">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>

</xs:schema>

=== rafalh/mtasa_toxic/toxic/conf/default/shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/shop.xsd">
	<item id="joinmsg" price="20000" />
	<item id="health100" price="100000" />
	<item id="flip" price="50000" />
	<item id="selfdestr" price="500000" />
	<item id="mine" price="200000" />
	<item id="oil" price="100000" />
	<item id="beer" price="2">
		<param name="seconds" value="20" />
	</item>
	<item id="invisibility" price="300000" />
	<item id="godmode30" price="300000">
		<param name="seconds" value="60" />
	</item>
	<item id="thunder" price="200000" />
	<item id="smoke" price="100000">
		<param name="seconds" value="15" />
	</item>
	<item id="spikestrip" price="200000" />
	<item id="nextmap" price="20000" />
	<item id="vip1w" price="3000000">
		<param name="days" value="3" />
	</item>
	<item id="team" price="1500000" />
</shop>
